# Generated by Django 6.0.3 on 2026-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_eventnotificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotificationread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
