# Generated by Django 5.0 on 2026-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_eventnotificationread_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotificationread',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='event_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('match', 'Match'), ('tournament', 'Tournament'), ('training', 'Strength Training'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
