# Generated by Django 6.0.3 on 2026-04-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_eventnotificationread_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotificationread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('maybe', 'Maybe'), ('not_attending', 'Not Attending')], default='attending', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.scheduledevent')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-responded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'player'), name='uniq_event_attendance_player')],
            },
        ),
    ]
