# Generated by Django 6.0.3 on 2026-04-05 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
        ("team_management", "0002_teammembership_request_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPresenceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255, unique=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_connections",
                        to="team_management.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "disconnected_at", "last_heartbeat_at"],
                        name="communicati_team_id_c3139e_idx",
                    ),
                    models.Index(
                        fields=["user", "disconnected_at"],
                        name="communicati_user_id_994b1e_idx",
                    ),
                ],
            },
        ),
    ]
