# Generated by Django 6.0.3 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_userpresenceconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementrecipient",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
