# Generated by Django 6.0.3 on 2026-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_management", "0003_alter_team_id_alter_teammembership_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
