# Generated by Django 6.0.3 on 2026-03-31 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0006_eventnotificationread_is_deleted'),
        ('team_management', '0002_teammembership_request_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], default='win', max_length=10)),
                ('points_scored', models.PositiveIntegerField(default=0)),
                ('points_conceded', models.PositiveIntegerField(default=0)),
                ('target_score', models.PositiveIntegerField(blank=True, null=True)),
                ('target_achieved', models.BooleanField(default=False)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('aces', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='scheduling.scheduledevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='team_management.teammembership')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_performance_records', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='team_management.team')),
            ],
            options={
                'ordering': ['-event__scheduled_at', 'member__user__first_name', 'member__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='uniq_performance_record_per_event_member')],
            },
        ),
    ]
