# Generated by Django 6.0.3 on 2026-03-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamperformancerecord',
            name='errors',
        ),
        migrations.AddField(
            model_name='teamperformancerecord',
            name='unforced_errors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
