# Generated by Django 6.0.3 on 2026-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_teamperformancerecord_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamperformancerecord',
            name='participation_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('did_not_attend', "Didn't Attend"), ('injured', 'Injured'), ('excused', 'Excused')], default='present', max_length=20),
        ),
    ]
