# Generated by Django 6.0.3 on 2026-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_teamperformancerecord_participation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamperformancerecord",
            name="injury_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minor_issue", "Minor Issue"),
                    ("recovering", "Recovering"),
                    ("recently_injured", "Recently Injured"),
                ],
                max_length=20,
            ),
        ),
    ]
