# Generated by Django 5.0 on 2026-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_teamperformancerecord_injury_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamperformancerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
