# Generated by Django 6.0.3 on 2026-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('login_2fa', 'Login 2FA'), ('password_reset', 'Password Reset')], max_length=30),
        ),
    ]
