# Generated by Django 6.0.3 on 2026-04-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_accountprofile_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parentchildlink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("announcements_enabled", models.BooleanField(default=True)),
                ("chat_enabled", models.BooleanField(default=True)),
                ("scheduling_enabled", models.BooleanField(default=True)),
                (
                    "announcement_digest",
                    models.CharField(
                        choices=[("instant", "Instant"), ("daily", "Daily digest")],
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "chat_digest",
                    models.CharField(
                        choices=[("instant", "Instant"), ("daily", "Daily digest")],
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "announcement_min_priority",
                    models.CharField(
                        choices=[
                            ("all", "All priorities"),
                            ("important_up", "Important & Urgent only"),
                            ("urgent_only", "Urgent only"),
                        ],
                        default="all",
                        max_length=15,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_start", models.TimeField(default="22:00")),
                ("quiet_end", models.TimeField(default="08:00")),
                (
                    "quiet_skip_entirely",
                    models.BooleanField(
                        default=False,
                        help_text="If True, notifications during quiet hours are dropped. If False, they are held and sent after quiet hours end.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preferences",
                "verbose_name_plural": "notification preferences",
            },
        ),
    ]
